[package]
name = "reservation"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid"] }
